### ISSUE TITLE
GoGoDuck Geoserver Configuration

### ISSUE THREAD

**Issue by fxmzb123** [aodn/geoserver-config#320]
Hi Dan,

Since the GoGoDuck is now part of the Geoserver, is it possible to document the configuration for it?

Thanks,
Ming

**Comment by danfruehauf** [comment]
@pblain We'll probably want to allocate time for that. @fxmzb123 wants to use GGD and I realized that it works well for us, but in order for other people to reuse it, we need to provide some documentation regarding:
 * How to configure metadata
 * How to configure GGD (`gogoduck.xml` in the geoserver directory)
 * Running GGD from the command line
   * How to debug things when they don't work

**Comment by danfruehauf** [comment]
> Hi Dan,
> 
> Since the GoGoDuck is now part of the Geoserver, is it possible to document the configuration for it?
> 
> Thanks,
> Ming

Next time when opening a ticket, you do not need to address me specifically. Also, this should not be formatted like an email, but more like a bug. It doesn't matter in this case because I understood your intention, but would be good for next time you report an issue.

This ticket should have been opened on aodn/geoserver-build, but I realized it only now.

**Comment by danfruehauf** [comment]
@fxmzb123 See aodn/geoserver-build#115
